### PR TITLE
[WIP] CMake building system + lib/ update

### PR DESCRIPTION
**Pull request by thinkingmaster**
- [ ] Update attach scripts?
- [x] Warning flags (and disabling warnings for 3rd party code)
- [x] Remove Makefile residue
- [x] Update README
- [x] Figure out mysterious crash on world load
- [x] Strip .so on release build
- [x] Make sure cathook compiles with different compile options
- [x] EnableNullGraphics = 1
- [x] EnableTextmodeStdin = 1
- [x] VACBypass = 1
- [x] GameSpecific = 0
- [x] Search for all leftovers of macros defined in Makefile, replace them by `#define`s from config.h
- [x] ENABLE_VISUALS
- [x] ENABLE_GUI
- [x] ENABLE_IPC
- [x] ENABLE_NULL_GRAPHICS
- [x] GAME (former `BUILD_GAME`)
- [x] ENABLE_TEXTMODE_STDIN (former `TEXTMODE_STDIN`)
- [x] ENABLE_VAC_BYPASS (former `TEXTMODE_VAC`)
- [x] DATA_PATH
- [x] Building cathook with CMake and injecting without instant crash.
- [x] Files in `lib` folder are updated with current versions from TF2/Steam binaries.
- [x] Some files from `lib` are removed because they are not needed, TF2 uses system ones.
- [x] Version info (git commit hash) in config.h.in
- [x] Config options from old Makefile
- [x] Fix the weird Timer{} crash
- [x] EnableGUI = 0
- [x] EnableVisuals = 0
- [x] EnableIPC = 1
- [x] ExternalDrawing = 1
- [x] Conditional source including for 
- [x] ENABLE_VISUALS
- [x] ENABLE_GUI
- [x] ENABLE_IPC
- [x] Something about data folder

### CODE REVIEW

**Comment by thinkingmaster** [comment]
This pull request is here to track the progress of porting cathook to CMake.

**Comment by BenCat07** [comment]
:thinking:

**Comment by thinkingmaster** [comment]
@BenCat07 xoverlay and glez will have to be installed separately (you already kinda have to do that). there's a `find_package` call to find those libs

**Comment by BenCat07** [comment]
Do you realize that cathook uses a libglez branch from me?

Jenny White <notifications@github.com> schrieb am Fr., 27. Apr. 2018, 20:42:

**Comment by thinkingmaster** [comment]
>Do you realize that cathook uses a libglez branch from me?

I will work on fixing all of this, don't worry, it's still WIP

**Comment by BenCat07** [comment]
Good.

Jenny White <notifications@github.com> schrieb am Fr., 27. Apr. 2018, 20:58:

**Comment by oneechanhax** [comment]
Hey uhh, here is some stuff you guys can use as examples, it should be pretty easy to use.
A project without dependencies nor meant to be used as one.
https://github.com/oneechanhax/nekohook/blob/master/CMakeLists.txt
and for using dependencies with cmake files
https://github.com/oneechanhax/nekobot/blob/master/CMakeLists.txt
and for  dependencies being included in other cmake files
https://github.com/oneechanhax/sleepy-discord/blob/master/CMakeLists.txt

**Comment by thinkingmaster** [comment]
Current TODO:

- Search for all leftovers of macros defined in Makefile, replace them by `#define`s from config.h
- Version info (git commit hash) in config.h.in
- Strip .so on release build
- Warning flags (and disabling warnings for 3rd party code)
- Data folder copying
- `.o`s from resource dir

**Comment by thinkingmaster** [comment]
At this point, this pull request is almost done - just a few things need to be done and tested.

**Comment by thinkingmaster** [comment]
Well, this thing is ready for merging, I guess.

**Pull request merged**
