### PR TITLE
Added missing descriptions + more

### PR DESCRIPTION
**Pull request by SylveonBottle**
Added lots of missing descriptions. Renamed a few 'modules' to make them shorter, while giving them more descriptive tooltips. Renamed AntiCheat to HackerDetector. Improved HealArrow default settings to values that I found worked _**extremely**_ well. Disabled "distance esp" from defaults. 

Maybe some more that I've forgotten.

### CODE REVIEW

**Comment by SylveonBottle** [comment]
Fixed misspell of "description".

**Comment by nullifiedcat** [comment]
sorry but this is unacceptable

**Comment by SylveonBottle** [comment]
Will now attempt compiling. Will fix errors as found.

**Comment by SylveonBottle** [comment]
Cathook built successfully. Will now test in-game.

**Comment by SylveonBottle** [comment]
Cathook successfully attached to TF2.

**Comment by oneechanhax** [comment]
Quite outdated any many descriptions and names changes for no needed reason.
You may re-create the pull request but please don't change default values, names that state what the feature does, and descriptions that describe what the feature does in detail. You may add information to features that don't already have information present in them.
If you don't know what a feature does, don't add information without looking at the code to see what it does or ask someone in the discord for more information about it.

**Pull request closed without merging**
